# --- Streamlit app for trip planning ---
import os
import streamlit as st
from crewai import Agent, Task, Crew, Process
from crewai_tools import SerperDevTool
from fpdf import FPDF
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from datetime import date, timedelta

# --- API KEYS & Secrets ---
# Ensure you have a .streamlit/secrets.toml file with these keys
try:
    os.environ["OPENAI_API_KEY"] = st.secrets["OPENAI_API_KEY"]
    os.environ["SERPER_API_KEY"] = st.secrets["SERPER_API_KEY"]
    SENDER_EMAIL = st.secrets["SENDER_EMAIL"]
    SENDER_PASSWORD = st.secrets["SENDER_PASSWORD"]
except (FileNotFoundError, KeyError):
    st.error("⚠️ Secrets file not found or missing keys. Please create a .streamlit/secrets.toml file.")
    st.stop()

# --- Function to create PDF from text ---
def create_pdf(text_content, traveler_name="", gender="", age="", start_date="", end_date=""):
    pdf = FPDF()
    pdf.add_page()

    # Header with color
    pdf.set_fill_color(41, 128, 185)  # Blue header
    pdf.rect(0, 0, 210, 40, 'F')

    # Title
    pdf.set_font("Arial", 'B', 24)
    pdf.set_text_color(255, 255, 255)
    pdf.set_y(10)
    pdf.cell(0, 15, txt="Vacation Plan", ln=True, align='C')

    # Subtitle with traveler info
    pdf.set_font("Arial", 'I', 12)
    if traveler_name:
        pdf.cell(0, 8, txt=f"Prepared for: {traveler_name}", ln=True, align='C')

    # Reset text color
    pdf.set_text_color(0, 0, 0)
    pdf.set_y(50)

    # Traveler details box
    if any([traveler_name, gender, age, start_date, end_date]):
        pdf.set_fill_color(236, 240, 241)
        pdf.rect(10, 45, 190, 30, 'F')
        pdf.set_font("Arial", 'B', 11)
        pdf.set_xy(15, 48)
        pdf.cell(0, 6, txt="Traveler Details", ln=True)
        pdf.set_font("Arial", size=10)
        details = []
        if gender:
            details.append(f"Gender: {gender}")
        if age:
            details.append(f"Age: {age}")
        if start_date and end_date:
            details.append(f"Travel Dates: {start_date} to {end_date}")
        pdf.set_xy(15, 56)
        pdf.cell(0, 6, txt="  |  ".join(details), ln=True)
        pdf.set_y(80)

    # Main content
    pdf.set_font("Arial", size=11)
    clean_text = text_content.encode('latin-1', 'replace').decode('latin-1')

    # Process text line by line for better formatting
    for line in clean_text.split('\n'):
        line = line.strip()
        if line.startswith('# '):
            pdf.set_font("Arial", 'B', 16)
            pdf.set_text_color(41, 128, 185)
            pdf.multi_cell(0, 10, txt=line[2:])
            pdf.set_text_color(0, 0, 0)
        elif line.startswith('## '):
            pdf.set_font("Arial", 'B', 14)
            pdf.set_text_color(52, 73, 94)
            pdf.multi_cell(0, 8, txt=line[3:])
            pdf.set_text_color(0, 0, 0)
        elif line.startswith('### '):
            pdf.set_font("Arial", 'B', 12)
            pdf.multi_cell(0, 7, txt=line[4:])
        elif line.startswith('- ') or line.startswith('* '):
            pdf.set_font("Arial", size=11)
            pdf.multi_cell(0, 6, txt="  " + line)
        elif line:
            pdf.set_font("Arial", size=11)
            pdf.multi_cell(0, 6, txt=line)
        else:
            pdf.ln(3)

    # Footer
    pdf.set_y(-20)
    pdf.set_font("Arial", 'I', 8)
    pdf.set_text_color(128, 128, 128)
    pdf.cell(0, 10, txt="Generated by AI Vacation Planner", align='C')

    return pdf.output(dest='S').encode('latin-1')

# --- Function to send email with PDF attachment ---
def send_email(recipient_email, pdf_data):
    msg = MIMEMultipart()
    msg['From'] = SENDER_EMAIL
    msg['To'] = recipient_email
    msg['Subject'] = "Your Vacation Plan"

    body = "Attached is your detailed vacation plan generated by your AI Travel Crew. Enjoy your trip!"
    msg.attach(MIMEText(body, 'plain'))

    part = MIMEBase('application', 'octet-stream')
    part.set_payload(pdf_data)
    encoders.encode_base64(part)
    part.add_header('Content-Disposition', 'attachment; filename="Vacation_Plan.pdf"')
    msg.attach(part)

    try:
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(SENDER_EMAIL, SENDER_PASSWORD)
        server.send_message(msg)
        server.quit()
        return True
    except Exception as e:
        st.error(f"Failed to send email: {e}")
        return False

# --- FUNCTION TO RUN THE CREW ---
def plan_vacation_trip(destination, trip_days, interests, departure_city):

    # Initialize Tools
    search_tool = SerperDevTool()

    # --- Defining Agents ---
    
    # 1. City Selector Agent
    city_selector = Agent(
        role='Expert Travel Agent',
        goal=f'Select the best specific city or region in {destination} for a {trip_days}-day vacation focusing on {interests}.',
        backstory='An experienced travel agent specializing in personalized trip planning who knows the best spots based on client interests.',
        tools=[search_tool], # GIVEN TOOL TO SEARCH
        verbose=True
    )
    
    # 2. Local Tour Guide Agent
    local_expert = Agent(
        role='Local Tour Guide',
        goal=f'Create a detailed {trip_days}-day itinerary with local attractions and food spots in {destination}.',
        backstory=f'A knowledgeable local guide for {destination} with deep insights into the best local experiences and hidden gems.',
        tools=[search_tool], # GIVEN TOOL TO SEARCH
        verbose=True
    )

    # 3. Logistics Manager Agent
    logistics_manager = Agent(
        role='Travel Logistics Manager',
        goal=f'Find the best flights from {departure_city} and accommodation options for the trip.',
        backstory='A meticulous planner who specializes in finding the most convenient and cost-effective travel options, including flights and hotels.',
        tools=[search_tool], # GIVEN TOOL TO SEARCH PRICES
        verbose=True
    )

    # 4. Report Compiler Agent
    report_compiler = Agent(
        role='Travel Plan Compiler',
        goal='Compile the city selection, itinerary, and logistics into a comprehensive, formatted travel plan.',
        backstory='An efficient assistant skilled at organizing information into a clear and comprehensive travel plan.',
        verbose=True
    )

    # --- Defining Tasks ---

    task_find_city = Task(
        description=f'Research and select the best single city or area in {destination} for a {trip_days}-day vacation that caters to {interests}. Explain why this city was chosen.',
        expected_output='The name of the single best city/area for the trip with a brief justification.',
        agent=city_selector     
    )

    task_plan_itinerary = Task(
        description=f"""Create a detailed, day-by-day itinerary for a {trip_days}-day trip to the selected city.
        First, use your search tool to find the top 5-10 tourist attractions and hidden gems suitable for {interests}.
        Then, organize these attractions into a logical daily schedule. 
        For each day, include specific places to visit and suggest authentic local food spots for lunch and dinner.""",
        expected_output=f'A detailed {trip_days}-day itinerary formatted as a list.',
        agent=local_expert,
        context=[task_find_city] # Pass the chosen city to this task
    )

    task_identify_logistics = Task(
        description=f"""Find current flight options from {departure_city} to the selected destination.
        Also, find 3 top-rated hotel or accommodation options for a {trip_days}-day stay.
        Include estimated prices where available.""",
        expected_output='A list of flight options (with estimated costs) and 3 recommended hotels (with descriptions and price range).',
        agent=logistics_manager,
        context=[task_find_city] # Pass the chosen city to this task
    )

    task_compile_report = Task(
        description="""Compile the results from the City Selection, Itinerary, and Logistics tasks into one well-structured travel document.
        Use clear headings (Introduction, Itinerary, Logistics) and bullet points.
        Ensure the tone is exciting and helpful.""",
        expected_output='A complete, professional travel plan document in markdown format.',
        agent=report_compiler,
        context=[task_find_city, task_plan_itinerary, task_identify_logistics] # Pass all previous outputs
    )

    # --- Assembling the Crew ---
    trip_crew = Crew(
        agents=[city_selector, local_expert, logistics_manager, report_compiler],
        tasks=[task_find_city, task_plan_itinerary, task_identify_logistics, task_compile_report],
        process=Process.sequential,
        verbose=True
    )

    # Kickoff the work
    result = trip_crew.kickoff()
    return result

# --- STREAMLIT UI ---
st.set_page_config(page_title="AI Vacation Planner", page_icon="✈️", layout="wide")

# Custom CSS for colors
st.markdown("""
<style>
    .main-header {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        padding: 20px;
        border-radius: 10px;
        margin-bottom: 20px;
    }
    .main-header h1 {
        color: white;
        text-align: center;
        margin: 0;
    }
    .main-header p {
        color: #e0e0e0;
        text-align: center;
        margin-top: 10px;
    }
    .stForm {
        background-color: #f8f9fa;
        padding: 20px;
        border-radius: 10px;
        border: 1px solid #e0e0e0;
    }
    div[data-testid="stFormSubmitButton"] > button {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        color: white;
        width: 100%;
        padding: 10px;
        font-size: 18px;
    }
    .section-header {
        background-color: #667eea;
        color: white;
        padding: 8px 15px;
        border-radius: 5px;
        margin: 15px 0 10px 0;
    }
</style>
""", unsafe_allow_html=True)

# Header
st.markdown("""
<div class="main-header">
    <h1>✈️ AI Vacation Planner</h1>
    <p>Enter your travel preferences and let the AI crew plan your perfect trip!</p>
</div>
""", unsafe_allow_html=True)

# Input fields for user preferences
with st.form("trip_form"):
    # Personal Information Section
    st.markdown('<p class="section-header">👤 Personal Information</p>', unsafe_allow_html=True)
    col1, col2, col3 = st.columns(3)
    with col1:
        traveler_name = st.text_input("Your Name", placeholder="Enter your name")
    with col2:
        gender = st.selectbox("Gender", ["Select", "Male", "Female", "Other", "Prefer not to say"])
    with col3:
        age = st.number_input("Age", min_value=1, max_value=120, value=25)

    # Travel Details Section
    st.markdown('<p class="section-header">🗺️ Travel Details</p>', unsafe_allow_html=True)
    col1, col2 = st.columns(2)
    with col1:
        departure_city = st.text_input("Departure City", "New York", placeholder="e.g., New York")
        destination = st.text_input("Destination", "Japan", placeholder="e.g., Japan")
    with col2:
        start_date = st.date_input("Start Date", date.today() + timedelta(days=30))
        end_date = st.date_input("End Date", date.today() + timedelta(days=37))

    # Preferences Section
    st.markdown('<p class="section-header">❤️ Preferences</p>', unsafe_allow_html=True)
    interests = st.text_input("Interests", "food, history", placeholder="e.g., food, history, adventure")

    # Calculate trip days from dates
    trip_days = (end_date - start_date).days + 1
    if trip_days < 1:
        st.warning("End date must be after start date!")
        trip_days = 1

    st.info(f"📅 Trip Duration: **{trip_days} days** ({start_date.strftime('%b %d, %Y')} to {end_date.strftime('%b %d, %Y')})")

    submitted = st.form_submit_button("🚀 Plan My Trip!")

# --- RUNNING THE CREW ---
if submitted:
    if trip_days < 1:
        st.error("Please select valid travel dates!")
    else:
        # Store user info in session state
        st.session_state['traveler_name'] = traveler_name
        st.session_state['gender'] = gender if gender != "Select" else ""
        st.session_state['age'] = age
        st.session_state['start_date'] = start_date.strftime('%b %d, %Y')
        st.session_state['end_date'] = end_date.strftime('%b %d, %Y')

        with st.spinner("🤖 The AI Crew is researching and planning your trip... (This may take 1-3 minutes)"):
            try:
                # Run the crew
                trip_plan = plan_vacation_trip(destination, trip_days, interests, departure_city)

                # Store result in session state to persist after reload
                st.session_state['trip_plan'] = trip_plan

            except Exception as e:
                st.error(f"An error occurred: {e}")

# --- DISPLAY & DOWNLOAD OPTIONS ---
if 'trip_plan' in st.session_state:
    st.markdown("""
    <div style="background: linear-gradient(135deg, #11998e 0%, #38ef7d 100%); padding: 15px; border-radius: 10px; margin: 20px 0;">
        <h3 style="color: white; margin: 0; text-align: center;">🎉 Your trip has been planned successfully!</h3>
    </div>
    """, unsafe_allow_html=True)

    # Get the raw text from the CrewOutput
    final_plan_text = str(st.session_state['trip_plan'])

    # Display traveler summary
    if st.session_state.get('traveler_name'):
        st.markdown(f"""
        <div style="background-color: #f0f8ff; padding: 15px; border-radius: 10px; border-left: 4px solid #667eea; margin-bottom: 20px;">
            <strong>Traveler:</strong> {st.session_state.get('traveler_name', 'N/A')} |
            <strong>Age:</strong> {st.session_state.get('age', 'N/A')} |
            <strong>Dates:</strong> {st.session_state.get('start_date', '')} - {st.session_state.get('end_date', '')}
        </div>
        """, unsafe_allow_html=True)

    # Display the plan
    st.markdown("---")
    st.markdown(final_plan_text)
    st.markdown("---")

    # PDF Logic with traveler details
    pdf_data = create_pdf(
        final_plan_text,
        traveler_name=st.session_state.get('traveler_name', ''),
        gender=st.session_state.get('gender', ''),
        age=str(st.session_state.get('age', '')),
        start_date=st.session_state.get('start_date', ''),
        end_date=st.session_state.get('end_date', '')
    )

    col_download, col_email = st.columns(2)

    with col_download:
        st.download_button(
            label="📄 Download Plan as PDF",
            data=pdf_data,
            file_name="Vacation_Plan.pdf",
            mime="application/pdf"
        )

    with col_email:
        with st.expander("📧 Email this Plan"):
            recipient_email = st.text_input("Recipient Email:")
            if st.button("Send Email"):
                if recipient_email:
                    with st.spinner("Sending email..."):
                        if send_email(recipient_email, pdf_data):
                            st.success(f"Email sent to {recipient_email}!")
                else:
                    st.warning("Please enter an email address.")